### ISSUE TITLE
Working with images without viewBox

### ISSUE THREAD

**Issue by artem-malko** [iamdarrenhall/gulp-svg-spritesheet#5]
Hi.

Sometimes, we've got svg without viewbox attr. So, this breaks plugin at string https://github.com/iamdarrenhall/gulp-svg-spritesheet/blob/master/index.js#L239. I'll try to fix it, but what do you think about it? Is there  any easy solutions?

Really cool plugin, i enjoy it)

**Comment by artem-malko** [comment]
@iamdarrenhall !up)

**Comment by iamdarrenhall** [comment]
This could be a difficult feature to add. The SVGs would need to have either a viewbox or a width and height on them, otherwise the only way to find the dimensions of the SVG would be to loop through each child element and parse it's coordinates in order to work out the maximum dimensions of the image.

**Comment by artem-malko** [comment]
@iamdarrenhall so, will it be implemented?

**Comment by iamdarrenhall** [comment]
I wouldn't implement parsing the SVGs child elements to calculate the SVG dimensions no, that would be madness. Checking for the width/height attribute of an SVG wouldn't be that difficult though.

**Comment by artem-malko** [comment]
@iamdarrenhall ok, thanks for explanation) Will try to implement it.

**Comment by iamdarrenhall** [comment]
Cool, send a pull request when you're done if you want :-)

**Comment by artem-malko** [comment]
@iamdarrenhall of course)
